import "./globals.css";
import { Merriweather, Montserrat } from "next/font/google";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const metadata = {
  title: "Espacio TEC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={merriweather.className}>{children}</body>
    </html>
  );
}
